name: ubuntu

on: [push, pull_request]

jobs:
  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
          submodules: recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install yarn
      run: curl -o- -L https://yarnpkg.com/install.sh | bash
    - name: Install dependencies
      run: yarn install --ignore-engines
    - name: Run tests 
      run: yarn test
      env: 
        CI: true
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}